-- PENDING.sql — the migrations this database has NOT run yet.
-- Verify afterwards with:  npm run check:tables
-- Regenerated by scripts/pending-migrations.sh

-- ============================================================
-- 0007_events.sql
-- ============================================================

-- 0007_events.sql — shabbat, chag and event registration. Replaces Flowiz.

create type event_kind        as enum ('shabbat','yomtov','event','payment_page');
create type registrant_kind   as enum ('adult','child','infant','donation','sale');
create type registration_state as enum ('pending','confirmed','cancelled','refunded');

create table events (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references tenants(id) on delete cascade,
  slug        text not null,
  kind        event_kind not null default 'shabbat',

  title       jsonb not null,                    -- {he, en}
  intro       jsonb not null default '{}'::jsonb,

  /** The occasion this was generated from, so the nightly job can find it
   *  again and never create a duplicate for the same shabbat. */
  occasion_key text,

  starts_on   date not null,                     -- first rest day
  ends_on     date not null,
  erev_on     date not null,

  is_open     boolean not null default true,
  is_listed   boolean not null default true,
  /** Registration closes this many hours before candle lighting, so there is
   *  time to shop and cook. */
  closes_hours_before int not null default 24,

  /** Set when a human edits a generated event, so the generator leaves it
   *  alone from then on. Losing a shliach's hand-written text to a cron job
   *  is the fastest way to make them stop trusting the system. */
  hand_edited boolean not null default false,

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  unique (tenant_id, slug),
  unique (tenant_id, occasion_key),
  check (ends_on >= starts_on and erev_on <= starts_on)
);

create index on events (tenant_id, starts_on) where is_open;

create trigger t_events_touch before update on events
  for each row execute function touch_updated_at();

create table event_meals (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null references tenants(id) on delete cascade,
  event_id   uuid not null references events(id) on delete cascade,
  name       jsonb not null,
  /** When the meal is served. Null start means "see the times board". */
  serves_at  timestamptz,
  location   jsonb not null default '{}'::jsonb,
  capacity   int,                                -- null = unlimited
  is_open    boolean not null default true,
  sort       int not null default 0
);

create index on event_meals (event_id, sort);

create table registrant_types (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references tenants(id) on delete cascade,
  meal_id     uuid not null references event_meals(id) on delete cascade,
  name        jsonb not null,
  kind        registrant_kind not null default 'adult',
  price_ils   numeric(10,2) not null default 0,
  /** Seats consumed per unit. A baby in arms takes none. */
  seats       int not null default 1,
  max_per_registration int not null default 20,
  sort        int not null default 0,
  check (price_ils >= 0 and seats >= 0)
);

create index on registrant_types (meal_id, sort);

create table registrations (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references tenants(id) on delete cascade,
  event_id    uuid not null references events(id) on delete cascade,
  code        text not null,

  full_name   text not null,
  email       text,
  phone       text not null,
  nationality text,
  notes       text,

  state       registration_state not null default 'pending',

  total_ils   numeric(10,2) not null default 0,
  donation_ils numeric(10,2) not null default 0,
  /** Set once a payment provider confirms. Null means nothing was charged. */
  paid_at     timestamptz,
  payment_ref text,

  track_token text not null default encode(gen_random_bytes(16), 'hex'),

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  unique (tenant_id, code)
);

create unique index on registrations (track_token);
create index on registrations (tenant_id, event_id, created_at desc);

create trigger t_registrations_touch before update on registrations
  for each row execute function touch_updated_at();

/** One line per registrant type chosen, with the price frozen at the time. */
create table registration_items (
  id              uuid primary key default gen_random_uuid(),
  tenant_id       uuid not null references tenants(id) on delete cascade,
  registration_id uuid not null references registrations(id) on delete cascade,
  meal_id         uuid not null references event_meals(id) on delete cascade,
  type_id         uuid not null references registrant_types(id) on delete cascade,
  qty             int not null check (qty > 0),
  unit_price_ils  numeric(10,2) not null,
  line_total_ils  numeric(10,2) not null
);

create index on registration_items (registration_id);

/**
 * Names of everyone attending.
 *
 * Kept separate from the registration because the house needs a head count
 * per meal by name — for seating, and because Sri Lanka asks for passport
 * names when guests sleep here.
 */
create table registration_participants (
  id              uuid primary key default gen_random_uuid(),
  tenant_id       uuid not null references tenants(id) on delete cascade,
  registration_id uuid not null references registrations(id) on delete cascade,
  meal_id         uuid references event_meals(id) on delete cascade,
  full_name       text not null,
  is_child        boolean not null default false,
  meal_choice     text,
  sort            int not null default 0
);

create index on registration_participants (registration_id, sort);

-- ---------------------------------------------------------------- counting

/**
 * Seats already taken for a meal. Counts only registrations that still
 * stand — a cancelled one must release its seats immediately, or a full
 * shabbat stays full after someone drops out.
 */
create or replace function meal_seats_taken(p_meal uuid)
returns int language sql stable as $$
  select coalesce(sum(i.qty * t.seats), 0)::int
    from registration_items i
    join registrant_types t on t.id = i.type_id
    join registrations r    on r.id = i.registration_id
   where i.meal_id = p_meal
     and r.state in ('pending', 'confirmed')
$$;

create or replace function meal_seats_left(p_meal uuid)
returns int language sql stable as $$
  select case
    when m.capacity is null then 2147483647       -- unlimited
    else greatest(m.capacity - meal_seats_taken(m.id), 0)
  end
  from event_meals m where m.id = p_meal
$$;

create or replace function next_registration_code(p_tenant uuid, p_event uuid)
returns text language plpgsql as $$
declare n int;
begin
  select count(*) + 1 into n from registrations
   where tenant_id = p_tenant and event_id = p_event;
  return 'R-' || lpad(n::text, 4, '0');
end $$;

-- ---------------------------------------------------------------- rls

alter table events                    enable row level security;
alter table event_meals               enable row level security;
alter table registrant_types          enable row level security;
alter table registrations             enable row level security;
alter table registration_items        enable row level security;
alter table registration_participants enable row level security;

-- The public may see an event and what it costs, but never who registered.
create policy events_read_public on events
  for select using (is_open);
create policy events_write on events
  for all using (app_can(tenant_id, 'staff')) with check (app_can(tenant_id, 'staff'));

create policy meals_read_public on event_meals for select using (true);
create policy meals_write on event_meals
  for all using (app_can(tenant_id, 'staff')) with check (app_can(tenant_id, 'staff'));

create policy types_read_public on registrant_types for select using (true);
create policy types_write on registrant_types
  for all using (app_can(tenant_id, 'staff')) with check (app_can(tenant_id, 'staff'));

-- No anonymous read on any registration table. A guest follows their own
-- registration through a token-scoped function, exactly like orders.
create policy regs_read_staff on registrations
  for select using (app_can(tenant_id, 'staff'));
create policy regs_write_staff on registrations
  for all using (app_can(tenant_id, 'staff')) with check (app_can(tenant_id, 'staff'));

create policy reg_items_staff on registration_items
  for all using (app_can(tenant_id, 'staff')) with check (app_can(tenant_id, 'staff'));
create policy reg_parts_staff on registration_participants
  for all using (app_can(tenant_id, 'staff')) with check (app_can(tenant_id, 'staff'));

-- ---------------------------------------------------------------- register

/**
 * Register for an event, as a guest.
 *
 * Same shape as place_order and for the same reason: the caller is not
 * signed in, so prices are rebuilt from registrant_types and capacity is
 * re-checked inside the writing transaction. Two people taking the last two
 * seats at the same moment cannot both succeed — the seat check and the
 * insert share one transaction, and the row lock on the meal serialises them.
 */
create or replace function place_registration(
  p_tenant      uuid,
  p_event       uuid,
  p_name        text,
  p_email       text,
  p_phone       text,
  p_nationality text,
  p_notes       text,
  p_lines       jsonb,   -- [{type_id, qty}]
  p_participants jsonb,  -- [{meal_id, full_name, is_child, meal_choice}]
  p_donation    numeric
)
returns table (registration_id uuid, registration_code text, track_token text, total numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event   events%rowtype;
  v_line    jsonb;
  v_type    registrant_types%rowtype;
  v_meal    event_meals%rowtype;
  v_qty     int;
  v_total   numeric(10,2) := 0;
  v_seats   jsonb := '{}'::jsonb;   -- meal_id -> seats requested
  v_key     text;
  v_id      uuid;
  v_code    text;
  v_token   text;
  v_part    jsonb;
begin
  select * into v_event from events
   where id = p_event and tenant_id = p_tenant;
  if not found then raise exception 'UNKNOWN_EVENT'; end if;
  if not v_event.is_open then raise exception 'CLOSED'; end if;

  if jsonb_array_length(coalesce(p_lines, '[]'::jsonb)) = 0 then
    raise exception 'NOTHING_SELECTED';
  end if;

  -- Lock the meals involved so concurrent registrations queue behind us.
  perform 1 from event_meals
   where event_id = p_event and tenant_id = p_tenant
   for update;

  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_qty := greatest(coalesce((v_line->>'qty')::int, 0), 0);
    if v_qty = 0 then continue; end if;

    select * into v_type from registrant_types
     where id = (v_line->>'type_id')::uuid and tenant_id = p_tenant;
    if not found then raise exception 'UNKNOWN_TYPE'; end if;
    if v_qty > v_type.max_per_registration then raise exception 'TOO_MANY'; end if;

    select * into v_meal from event_meals
     where id = v_type.meal_id and event_id = p_event;
    if not found then raise exception 'TYPE_NOT_IN_EVENT'; end if;
    if not v_meal.is_open then raise exception 'MEAL_CLOSED:%', v_meal.name->>'he'; end if;

    v_key := v_meal.id::text;
    v_seats := jsonb_set(
      v_seats, array[v_key],
      to_jsonb(coalesce((v_seats->>v_key)::int, 0) + v_qty * v_type.seats),
      true
    );

    v_total := v_total + v_type.price_ils * v_qty;
  end loop;

  -- Capacity, checked after totalling so one request cannot overshoot by
  -- spreading the same meal across several lines.
  for v_key in select jsonb_object_keys(v_seats) loop
    if meal_seats_left(v_key::uuid) < (v_seats->>v_key)::int then
      select * into v_meal from event_meals where id = v_key::uuid;
      raise exception 'FULL:%', v_meal.name->>'he';
    end if;
  end loop;

  v_total := v_total + greatest(coalesce(p_donation, 0), 0);
  v_code  := next_registration_code(p_tenant, p_event);
  v_token := encode(gen_random_bytes(16), 'hex');

  insert into registrations (
    tenant_id, event_id, code, full_name, email, phone,
    nationality, notes, total_ils, donation_ils, track_token
  ) values (
    p_tenant, p_event, v_code, p_name, nullif(trim(coalesce(p_email,'')),''), p_phone,
    nullif(trim(coalesce(p_nationality,'')),''), nullif(trim(coalesce(p_notes,'')),''),
    v_total, greatest(coalesce(p_donation,0),0), v_token
  )
  returning id into v_id;

  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_qty := greatest(coalesce((v_line->>'qty')::int, 0), 0);
    if v_qty = 0 then continue; end if;
    select * into v_type from registrant_types where id = (v_line->>'type_id')::uuid;

    insert into registration_items (
      tenant_id, registration_id, meal_id, type_id, qty, unit_price_ils, line_total_ils
    ) values (
      p_tenant, v_id, v_type.meal_id, v_type.id, v_qty,
      v_type.price_ils, v_type.price_ils * v_qty
    );
  end loop;

  for v_part in select * from jsonb_array_elements(coalesce(p_participants, '[]'::jsonb)) loop
    if coalesce(trim(v_part->>'full_name'), '') = '' then continue; end if;
    insert into registration_participants (
      tenant_id, registration_id, meal_id, full_name, is_child, meal_choice
    ) values (
      p_tenant, v_id,
      nullif(v_part->>'meal_id','')::uuid,
      trim(v_part->>'full_name'),
      coalesce((v_part->>'is_child')::boolean, false),
      nullif(trim(coalesce(v_part->>'meal_choice','')), '')
    );
  end loop;

  return query select v_id, v_code, v_token, v_total;
end $$;

revoke all on function place_registration(uuid, uuid, text, text, text, text, text,
  jsonb, jsonb, numeric) from public;

/** What a registrant may see about their own registration. */
create or replace function registration_tracking(p_token text)
returns table (
  code text, state registration_state, event_title jsonb,
  starts_on date, ends_on date, total_ils numeric, paid_at timestamptz,
  lines jsonb
)
language sql stable security definer set search_path = public as $$
  select r.code, r.state, e.title, e.starts_on, e.ends_on, r.total_ils, r.paid_at,
         (select jsonb_agg(jsonb_build_object(
                   'meal', m.name->>'he',
                   'type', t.name->>'he',
                   'qty',  i.qty,
                   'line', i.line_total_ils))
            from registration_items i
            join registrant_types t on t.id = i.type_id
            join event_meals m      on m.id = i.meal_id
           where i.registration_id = r.id)
    from registrations r
    join events e on e.id = r.event_id
   where r.track_token = p_token
$$;

revoke all on function registration_tracking(text) from public;
grant execute on function registration_tracking(text) to anon, authenticated;

-- ============================================================
-- 0008_content.sql
-- ============================================================

-- 0008_content.sql — gallery, the about section, articles and their comments.

create type media_kind    as enum ('photo','video');
create type comment_state as enum ('pending','approved','rejected');

-- ---------------------------------------------------------------- gallery

create table media_items (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null references tenants(id) on delete cascade,
  kind       media_kind not null default 'photo',

  /** A photo lives in storage. A video is a link to YouTube or Vimeo —
   *  hosting video on Supabase would be expensive and slow to serve into
   *  Sri Lanka, and every phone already plays an embed. */
  storage_path text,
  external_url text,
  /** Still frame for a video, so the grid is not a row of grey boxes. */
  poster_path  text,

  caption    jsonb not null default '{}'::jsonb,
  album      text  not null default 'general',
  taken_on   date,

  sort       int not null default 0,
  is_active  boolean not null default true,
  /** Shown in the strip on the home page, not only in the full gallery. */
  is_featured boolean not null default false,

  width_px   int,
  height_px  int,
  bytes      int,
  created_at timestamptz not null default now(),

  constraint photo_needs_file  check (kind <> 'photo' or storage_path is not null),
  constraint video_needs_link  check (kind <> 'video' or external_url is not null)
);

create index on media_items (tenant_id, album, sort) where is_active;
create index on media_items (tenant_id, sort) where is_active and is_featured;

-- ---------------------------------------------------------------- about

/**
 * One row per tenant. A table rather than a settings blob so the two
 * portraits get real columns — they are uploaded and deleted like any other
 * file and should not be buried in JSON.
 */
create table site_about (
  tenant_id  uuid primary key references tenants(id) on delete cascade,
  heading    jsonb not null default '{}'::jsonb,
  body       jsonb not null default '{}'::jsonb,   -- {he, en}, plain paragraphs

  shluchim_path    text,
  shluchim_caption jsonb not null default '{}'::jsonb,
  rebbe_path       text,
  rebbe_caption    jsonb not null default '{}'::jsonb,

  updated_at timestamptz not null default now()
);

create trigger t_about_touch before update on site_about
  for each row execute function touch_updated_at();

-- ---------------------------------------------------------------- articles

create table articles (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null references tenants(id) on delete cascade,
  slug       text not null,

  title      jsonb not null,
  excerpt    jsonb not null default '{}'::jsonb,
  /** Markdown. Rendered to a restricted subset — see the renderer. */
  body       jsonb not null default '{}'::jsonb,

  cover_path text,
  read_minutes int not null default 4,

  is_published boolean not null default false,
  published_at timestamptz,
  sort       int not null default 0,

  /** Comments can be switched off per article. */
  comments_open boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (tenant_id, slug)
);

create index on articles (tenant_id, published_at desc) where is_published;

create trigger t_articles_touch before update on articles
  for each row execute function touch_updated_at();

create table article_comments (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null references tenants(id) on delete cascade,
  article_id uuid not null references articles(id) on delete cascade,

  author_name  text not null,
  author_email text,
  body         text not null,

  /**
   * Nothing appears on the site until a human approves it. An open comment
   * box on a Chabad house site is a spam magnet, and the shliach should
   * never have to discover that from a visitor.
   */
  state      comment_state not null default 'pending',
  /** Staff may correct a typo or trim abuse; the original is kept so an
   *  edit can be shown to be an edit rather than a silent rewrite. */
  edited_body text,
  edited_at   timestamptz,

  created_at timestamptz not null default now(),

  constraint body_not_empty check (length(trim(body)) > 0)
);

create index on article_comments (article_id, created_at desc);
create index on article_comments (tenant_id, state) where state = 'pending';

/** What the public sees: the edited text when staff changed it. */
create or replace function comment_display_body(c article_comments)
returns text language sql immutable as $$
  select coalesce(c.edited_body, c.body)
$$;

-- ---------------------------------------------------------------- rls

alter table media_items      enable row level security;
alter table site_about       enable row level security;
alter table articles         enable row level security;
alter table article_comments enable row level security;

create policy media_read_public on media_items for select using (is_active);
create policy media_write on media_items
  for all using (app_can(tenant_id, 'staff')) with check (app_can(tenant_id, 'staff'));

create policy about_read_public on site_about for select using (true);
create policy about_write on site_about
  for all using (app_can(tenant_id, 'admin')) with check (app_can(tenant_id, 'admin'));

create policy articles_read_public on articles for select using (is_published);
create policy articles_write on articles
  for all using (app_can(tenant_id, 'staff')) with check (app_can(tenant_id, 'staff'));

-- Only approved comments are readable by anyone; pending ones are staff-only.
create policy comments_read_public on article_comments
  for select using (state = 'approved');
create policy comments_manage on article_comments
  for all using (app_can(tenant_id, 'staff')) with check (app_can(tenant_id, 'staff'));

-- ---------------------------------------------------------------- storage

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('content', 'content', true, 10485760,
        array['image/jpeg','image/png','image/webp','image/avif'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

create policy content_images_read on storage.objects
  for select using (bucket_id = 'content');

create policy content_images_write on storage.objects
  for insert to authenticated
  with check (bucket_id = 'content'
    and public.app_can(((storage.foldername(name))[1])::uuid, 'staff'));

create policy content_images_update on storage.objects
  for update to authenticated
  using (bucket_id = 'content'
    and public.app_can(((storage.foldername(name))[1])::uuid, 'staff'));

create policy content_images_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'content'
    and public.app_can(((storage.foldername(name))[1])::uuid, 'staff'));

-- ---------------------------------------------------------------- comment submission

/**
 * Leave a comment, as a guest.
 *
 * Runs as definer because the caller is anonymous and RLS would block the
 * insert. It can only ever create a 'pending' row — the state is set here,
 * not taken from the caller — so a forged request cannot self-approve.
 */
create or replace function post_comment(
  p_tenant  uuid,
  p_article uuid,
  p_name    text,
  p_email   text,
  p_body    text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_article articles%rowtype;
  v_recent  int;
  v_id      uuid;
begin
  select * into v_article from articles
   where id = p_article and tenant_id = p_tenant and is_published;
  if not found then raise exception 'UNKNOWN_ARTICLE'; end if;
  if not v_article.comments_open then raise exception 'COMMENTS_CLOSED'; end if;

  if length(trim(coalesce(p_body, ''))) < 2 then raise exception 'EMPTY'; end if;
  if length(p_body) > 2000 then raise exception 'TOO_LONG'; end if;

  -- Crude flood guard: a handful per article per hour from one name.
  select count(*) into v_recent from article_comments
   where article_id = p_article
     and author_name = trim(p_name)
     and created_at > now() - interval '1 hour';
  if v_recent >= 3 then raise exception 'TOO_MANY'; end if;

  insert into article_comments (tenant_id, article_id, author_name, author_email, body)
  values (p_tenant, p_article, trim(p_name),
          nullif(trim(coalesce(p_email,'')),''), trim(p_body))
  returning id into v_id;

  return v_id;
end $$;

revoke all on function post_comment(uuid, uuid, text, text, text) from public;

-- ============================================================
-- 0009_dish_photos.sql
-- ============================================================

-- 0009_dish_photos.sql — several photos per dish, not one.

create table menu_item_images (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null references tenants(id) on delete cascade,
  item_id    uuid not null references menu_items(id) on delete cascade,

  storage_path text not null,
  alt          jsonb not null default '{}'::jsonb,

  sort       int not null default 0,
  width_px   int,
  height_px  int,
  bytes      int,
  created_at timestamptz not null default now()
);

create index on menu_item_images (item_id, sort);

alter table menu_item_images enable row level security;

-- Visible wherever the dish is visible.
create policy dish_images_read_public on menu_item_images
  for select using (
    exists (
      select 1 from menu_items i
      join menu_categories c on c.id = i.category_id
      where i.id = menu_item_images.item_id and c.is_active
    )
  );

create policy dish_images_write on menu_item_images
  for all using (app_can(tenant_id, 'staff'))
  with check (app_can(tenant_id, 'staff'));

/**
 * Carry the existing single photo over as the first image, so nothing that
 * was already uploaded disappears when the menu starts reading from here.
 * menu_items.image_path stays as the thumbnail for lists.
 */
insert into menu_item_images (tenant_id, item_id, storage_path, sort)
select tenant_id, id, image_path, 0
  from menu_items
 where image_path is not null
on conflict do nothing;

-- ============================================================
-- 0010_happenings.sql
-- ============================================================

-- 0010_happenings.sql — the noticeboard: classes, farbrengens, announcements.

create type happening_kind  as enum ('class','farbrengen','notice','event');
create type happening_cycle as enum ('once','weekly','monthly');

create table happenings (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null references tenants(id) on delete cascade,

  kind       happening_kind  not null default 'class',
  cycle      happening_cycle not null default 'weekly',

  title      jsonb not null,
  details    jsonb not null default '{}'::jsonb,
  -- Free text such as "for men" or "whole family", written in the admin.
  -- Kept out of this file as a literal: Hebrew in a .sql is corrupted by a
  -- clipboard round-trip, which already happened once on this project.
  -- Free text such as "for men" or "whole family", written in the admin.
  -- Kept out of this file as a literal: Hebrew in a .sql is corrupted by a
  -- clipboard round-trip, which already happened once on this project.
  audience   jsonb not null default '{}'::jsonb,
  location   jsonb not null default '{}'::jsonb,

  /** weekly: 0=Sunday … 6=Saturday. Null for one-off. */
  weekday    int check (weekday between 0 and 6),
  /** monthly: nth weekday, e.g. 1 = first Tuesday. */
  week_of_month int check (week_of_month between 1 and 5),
  /** once: the actual date. */
  on_date    date,

  starts_at  time,
  ends_at    time,

  /**
   * Times that follow the sun rather than the clock: a class "after mincha"
   * moves every week. Stored as an offset from a zman so the board is right
   * without anyone editing it.
   */
  anchor     text,                                  -- 'candle_lighting' | 'sunset' | 'tzeis' | null
  anchor_offset_min int not null default 0,

  is_active  boolean not null default true,
  /** Paused for the season rather than deleted — Arugam Bay empties out
   *  between November and March and the classes come back. */
  paused_note jsonb not null default '{}'::jsonb,

  sort       int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint weekly_needs_weekday  check (cycle <> 'weekly'  or weekday is not null),
  constraint monthly_needs_weekday check (cycle <> 'monthly' or (weekday is not null and week_of_month is not null)),
  constraint once_needs_date       check (cycle <> 'once'    or on_date is not null),
  constraint has_a_time            check (starts_at is not null or anchor is not null)
);

create index on happenings (tenant_id, sort) where is_active;

create trigger t_happenings_touch before update on happenings
  for each row execute function touch_updated_at();

alter table happenings enable row level security;

create policy happenings_read_public on happenings for select using (is_active);
create policy happenings_write on happenings
  for all using (app_can(tenant_id, 'staff')) with check (app_can(tenant_id, 'staff'));

-- ============================================================
-- 0011_printing.sql
-- ============================================================

-- 0011_printing.sql — printers, the print queue, and the receipt template.

create type printer_kind      as enum ('receipt','kitchen','bar');
create type printer_transport as enum ('cloudprnt','agent','browser');
create type print_status      as enum ('queued','claimed','printed','failed');

create table printers (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null references tenants(id) on delete cascade,

  name       text not null,
  kind       printer_kind not null default 'receipt',
  transport  printer_transport not null default 'browser',

  /**
   * Which stations this printer is responsible for. A kitchen printer by
   * the grill should not spit out the bar's drinks.
   */
  stations   text[] not null default '{}',

  paper_width int not null default 80 check (paper_width in (58, 80)),
  /** Shared secret a polling printer presents; never leaves the admin. */
  poll_token text not null default encode(gen_random_bytes(16), 'hex'),
  last_seen_at timestamptz,

  is_active  boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index on printers (poll_token);
create index on printers (tenant_id) where is_active;

create table print_jobs (
  id         bigserial primary key,
  tenant_id  uuid not null references tenants(id) on delete cascade,
  printer_id uuid not null references printers(id) on delete cascade,
  order_id   uuid references orders(id) on delete cascade,

  template   text not null default 'receipt',
  /** Rendered lines, so a reprint is byte-identical to the original even
   *  after the menu or the template changes. */
  payload    jsonb not null,

  status     print_status not null default 'queued',
  attempts   int not null default 0,
  error      text,

  created_at timestamptz not null default now(),
  claimed_at timestamptz,
  printed_at timestamptz
);

create index on print_jobs (printer_id, status, created_at);
create index on print_jobs (order_id);

/** Per-tenant receipt layout, edited in the admin with a live preview. */
create table receipt_template (
  tenant_id   uuid primary key references tenants(id) on delete cascade,

  -- Free text lines, e.g. the house name and address. Kept out of this file
  -- as literals: Hebrew in a .sql is corrupted by a clipboard round-trip.
  header_lines jsonb not null default '[]'::jsonb,
  footer_lines jsonb not null default '[]'::jsonb,
  show_logo    boolean not null default true,
  show_qr      boolean not null default true,
  show_prices  boolean not null default true,
  /** Kitchen tickets deliberately omit money — a cook does not need it and
   *  it is one more thing to misread at speed. */
  kitchen_show_prices boolean not null default false,
  paper_width  int not null default 80 check (paper_width in (58, 80)),

  updated_at  timestamptz not null default now()
);

create trigger t_receipt_touch before update on receipt_template
  for each row execute function touch_updated_at();

alter table printers         enable row level security;
alter table print_jobs       enable row level security;
alter table receipt_template enable row level security;

create policy printers_staff on printers
  for all using (app_can(tenant_id, 'staff')) with check (app_can(tenant_id, 'staff'));
create policy jobs_staff on print_jobs
  for all using (app_can(tenant_id, 'kitchen')) with check (app_can(tenant_id, 'kitchen'));
create policy receipt_read_staff on receipt_template
  for select using (app_can(tenant_id, 'kitchen'));
create policy receipt_write on receipt_template
  for all using (app_can(tenant_id, 'staff')) with check (app_can(tenant_id, 'staff'));

/**
 * Hand the next queued job to a polling printer, exactly once.
 *
 * `for update skip locked` is what makes two printers polling the same
 * moment safe: each takes a different row instead of both taking the same
 * one and printing the order twice.
 */
create or replace function claim_print_job(p_token text)
returns table (job_id bigint, template text, payload jsonb)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_printer printers%rowtype;
  v_job     print_jobs%rowtype;
begin
  select * into v_printer from printers where poll_token = p_token and is_active;
  if not found then raise exception 'UNKNOWN_PRINTER'; end if;

  update printers set last_seen_at = now() where id = v_printer.id;

  select * into v_job
    from print_jobs
   where printer_id = v_printer.id and status = 'queued'
   order by created_at
   for update skip locked
   limit 1;

  if not found then return; end if;

  update print_jobs
     set status = 'claimed', claimed_at = now(), attempts = attempts + 1
   where id = v_job.id;

  return query select v_job.id, v_job.template, v_job.payload;
end $$;

revoke all on function claim_print_job(text) from public;

create or replace function confirm_print_job(p_token text, p_job bigint, p_ok boolean, p_error text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_printer printers%rowtype;
begin
  select * into v_printer from printers where poll_token = p_token and is_active;
  if not found then raise exception 'UNKNOWN_PRINTER'; end if;

  update print_jobs
     set status = case when p_ok then 'printed' else 'failed' end,
         printed_at = case when p_ok then now() else null end,
         error = p_error
   where id = p_job and printer_id = v_printer.id;
end $$;

revoke all on function confirm_print_job(text, bigint, boolean, text) from public;

-- Default template for the single tenant. Hebrew is inserted from the app on
-- first load, not from this file, for the encoding reason noted above.
insert into receipt_template (tenant_id)
select id from tenants
on conflict (tenant_id) do nothing;

-- ============================================================
-- 0012_site_text.sql
-- ============================================================

-- 0012_site_text.sql — editable copy for the public pages.

/**
 * Overrides, not storage.
 *
 * Every string also exists as a default in the code, so a missing row, an
 * unrun migration or a typo in a key can never leave a blank page. A row
 * here only replaces what the code already says.
 */
create table site_text (
  tenant_id  uuid not null references tenants(id) on delete cascade,
  key        text not null,
  value      jsonb not null,            -- {he, en}
  updated_at timestamptz not null default now(),
  primary key (tenant_id, key)
);

create trigger t_site_text_touch before update on site_text
  for each row execute function touch_updated_at();

alter table site_text enable row level security;

create policy site_text_read_public on site_text
  for select using (true);

create policy site_text_write on site_text
  for all using (app_can(tenant_id, 'staff'))
  with check (app_can(tenant_id, 'staff'));

-- ============================================================
-- 0013_receipt_media.sql
-- ============================================================

-- 0013_receipt_media.sql — logo and banner images on the printed receipt.

alter table receipt_template
  /** Small mark above the header lines. */
  add column if not exists logo_path text,
  /** Full-width banner at the very top, before the logo. */
  add column if not exists header_image_path text,
  /** Full-width banner at the very bottom, after the footer lines. */
  add column if not exists footer_image_path text;

/**
 * Receipt artwork lives in its own bucket.
 *
 * Separate from 'menu' so that a staff member who may edit dish photos
 * cannot necessarily alter what is printed on every receipt, and so the
 * size limit can be much smaller: a thermal printer renders 576 pixels
 * wide and anything larger is wasted bandwidth on every poll.
 */
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('receipt', 'receipt', true, 2097152,
        array['image/png','image/jpeg','image/webp'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

create policy receipt_media_read on storage.objects
  for select using (bucket_id = 'receipt');

create policy receipt_media_write on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'receipt'
    and public.app_can(((storage.foldername(name))[1])::uuid, 'staff')
  );

create policy receipt_media_update on storage.objects
  for update to authenticated
  using (
    bucket_id = 'receipt'
    and public.app_can(((storage.foldername(name))[1])::uuid, 'staff')
  );

create policy receipt_media_delete on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'receipt'
    and public.app_can(((storage.foldername(name))[1])::uuid, 'staff')
  );
